version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './html:/var/www/html'
    ports:
      - '8000:80'
    restart: always
    depends_on:
      - php

  php:
    image: php:8.2.14-fpm
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    # ports:
    #   - 9000:9000
    volumes:
      - './html:/var/www/html'
      # - ./php/conf.d:/usr/local/etc/php/conf.d
      # - ./log/php:/usr/local/php/log


  # composer:
  #     image: 'composer'
  #     volumes:
  #         - './web/app:/app'
  #     command: install
