services:
  mysql:
    # build 和 image 二选一
    # build: 自己构建镜像
    # image: 使用已经构建好的镜像
    build:
      context: ./dir # context 选项可以是 Dockerfile 的文件路径，也可以是到链接到 git 仓库的 url
      dockerfile: path/of/Dockerfile # 使用此 dockerfile 文件来构建，必须指定构建路径
    image: mysql:5.7.39 # 镜像名称
    restart: always
    hostname: mysql
    container_name: mysql-main # 容器名称
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1  # 覆盖容器启动后默认执行的命令
    privileged: true

    env_file: .env
    # env_file:
    #   - .env

    working_dir: /usr/src/mymaven # gongzuomulu
    tty: true

    network_mode: 'host'
    ports:
      #  HOST:CONTAINER
      - 3306:3306 # 端口
      #- 127.0.0.1:8889:8889
    environment:
      - MYSQL_ROOT_PASSWORD=123456 # root 密码
      - MYSQL_DATABASE=main # 数据库
      - TZ=Asia/Shanghai
      - MYSQL_USER=test #创建test用户
      - MYSQL_PASSWORD=test #设置test用户的密码
    volumes:
      - ./data/:/var/lib/mysql/
      - ./log/:/logs

      # --mount type=bind,source=/path/to/media,target=/media,readonly
      - type: bind
        source: /path/to/media2
        target: /media2
        read_only: true
    devices:
      - /dev/dri/:/dev/dri/ # --device /dev/dri/:/dev/dri/
    networks:
      default:
        ipv4_address: 192.168.1.2 # 同网段IP

networks:
  default:
    name: wqdy
    external: true

