version: '3.9'
services:
  mysql:
    image: mysql:5.7.39
    restart: always
    hostname: mysql
    container_name: mysql-main
    privileged: true
    env_file: .env
    working_dir: /usr/src/mymaven # gongzuomulu
    tty: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456 # root 密码
      - MYSQL_DATABASE=main # 数据库
      - TZ=Asia/Shanghai
      - MYSQL_USER=test #创建test用户
      - MYSQL_PASSWORD=test #设置test用户的密码
    volumes:
      - ./data/:/var/lib/mysql/
      - ./log/:/logs
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
    networks:
      default:
        ipv4_address: 192.168.1.2 # 同网段IP

networks:
  default:
    external:
      name: wqdy
